site_name: 'Documentation'
theme:
    name: 'material'
    logo: 'images/logo.png'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'

    palette:
        primary: 'brown'
        accent: 'brown'

nav:
    - 'Home': 'index.md'
    - 'Markdown Syntax': 'markdown-syntax.md'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

copyright: 'Copyright &copy; 2019 - 2020 David Creus'
